[package]
name = "sys_monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
strum = { version = "0.23", features = ["derive"]}
chrono = "0.4"
widestring = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
bytemuck = "1.1"
serde = { version = "1.0" }
serde_json = "1.0"

[dependencies.windows]
version = "0.51"
features = [
    "Win32_Foundation",
    "Win32_System_Time",
    "Win32_Security",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Etw",
    "Win32_System_SystemInformation"
]